### ISSUE TITLE
Breaking layout when using eminiarts/nova-tabs package

### ISSUE THREAD

**Issue by stufarquhar** [codenco-dev/nova-grid-system#5] opened 2020-06-04 01:15 UTC
This simply does not work when using eminiarts/nova-tabs in detail view. It does however work without the use of tabs thou. 

see image. 
![Screen Shot 2020-06-04 at 1 13 45 PM](https://user-images.githubusercontent.com/24727686/83704105-46ebfd00-a665-11ea-8a16-f4071a44e844.png)

**Comment by vbezruchkin** [comment] 2020-06-25 12:26
Hi,

I have the same problem. Do you expect any fix for this?

Thanks

**Closed** 2020-07-07 08:21 UTC
Labels: enhancement

**Comment by thomasdominic** [comment] 2020-07-07 08:24
@stufarquhar @vbezruchkin Can you check if this release fix your problem ?

https://github.com/codenco-dev/nova-grid-system/releases/tag/1.0.1

I don't know if the problem wasn't with breadcrumb for example.

Thanks for your feedback

**Comment by vbezruchkin** [comment] 2020-07-07 08:45
Hi,

Thanks for the fix. Worked fine for me.

![image](https://user-images.githubusercontent.com/2760455/86751460-7d4fda00-c060-11ea-8f6f-20ad984d2141.png)

Cheers

**Comment by thomasdominic** [comment] 2020-07-12 08:37
@stufarquhar Have you got a feedback ?

**Comment by happyDemon** [comment] 2020-07-13 08:42
@thomasdominic I still have an issue here,
basically all fields are shown in 1 row when in tab-view, if I disable tabs there's no problem

**Comment by thomasdominic** [comment] 2020-07-17 07:28
@happyDemon Can you post a new issue on this repo and give me an example of resource ? I will try to look at this

**Comment by happyDemon** [comment] 2020-07-17 07:39
@thomasdominic  the main difference with @vbezruchkin is that I used the TabsOnEdit trait on my resource (his screenshot just shows the standard nova form-layout).

<img width="921" alt="Screenshot 2020-07-13 at 10 43 24" src="https://user-images.githubusercontent.com/38573/87761155-43759500-c811-11ea-96c4-9563908cc83d.png">

The issue is that nova-tabs uses a custom component based on PanelItem in this case and the container didn't have `flex-wrap`, which is why all fields were rendered on 1 line.

I sent a PR to nova-tabs, in the meantime I tagged my repo so I could use it in my own projects in the meantime, @eminiarts doesn't seem to be very responsive when I look at all the open PRs.

**Comment by thomasdominic** [comment] 2020-07-17 07:45
Okay :)
I hope my package is cool for you :)

**Comment by happyDemon** [comment] 2020-07-17 07:54
this is a killer package :D it's so weird nova doesn't support this out of the box

**Comment by thomasdominic** [comment] 2020-07-17 08:06
@happyDemon hey thanks, don't hesitate to talk about it then :)
